### ISSUE TITLE
Final Getsuga reset fails if the user doesn't know Double Punch.

### ISSUE THREAD

**Issue by AndrioCelos** [Iyouboushi/mIRC-BattleArena#16]
This was reported by a bot admin named Fasa in #BattleArena yesterday.
It turned out this happened:
`/writeini: insufficient parameters (line 3306, systemaliases.als)`

**Comment by Iyouboushi** [comment]
Fixed.

**Comment by AndrioCelos** [comment]
FYI: you can close it by writing something like `Fixes #16.` in the commit message, too.
https://help.github.com/articles/closing-issues-via-commit-messages/
