### ISSUE TITLE
Help request modify a boss

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#32]
I Want to Modify i my network the Boss Kingslime for this..
You know a Slime in the Game Minecraft when you kill them than spawn a random few smaller slimes 

But what must i set up in the file for example
when a player kills the KingSlime... than spawns 1 or 3 smaller slimes
do you know what i mean ?

**Comment by Pentium320** [comment]
I think, that the way it should be done is using **SpawnAfterDeath** in **[Info]** section of monsters .char file...
...however:

1. You need .char file with another monster, so - in your example, create new monster (Slime), optionally you can use already existing monsters (Red Slime, Blue Slime, etc.). You can find how it's done, for instance in those monsters: MotherBrain.char, Daos.char, Jailor_of_Love.char
2. I'm not sure, if this flag was meant to be used to spawn multiple monsters. I would try with separating them with dots, though I have no idea, if it works. If not... well, this can be a feature request in future update then.

**Comment by Serpano** [comment]
hmmm can i set a $iif?

**Comment by Serpano** [comment]
for example :  SpawnAfterDeath=$iif($rand(1,3) = 3, Blue_slime.red_slime.green_slime) so? i think

**Comment by Pentium320** [comment]
Basically, $iif has just same concept as normal "if" function, but is written in one line to keep code simplier and cleaner. The way you wrote it above just won't work. To randomize spawned monsters you may want to check **$gettok** function.

This tutorial in section **3a** nicely explains **$gettok** function: http://www.mirc.org/mishbox/tutorials/tokens.htm#s3a

Anyway, it's just randomization, it won't spawn multiple monsters. And I'm not sure, if it's possible without making some changes in bots code.

**Comment by Serpano** [comment]
when i use $iif , can i add more clauses ?

for example SpawnAfterDeath=$iif($rand(1,3) = 3, BlueSlime.RedSlime.Greenslime,$rand(1,3) = 2 etc... )
You know what i meen ? the $gettock feature are for me to complicated

**Comment by Serpano** [comment]
Or i think can i activate the monster summon skill if the enemys hp is 1 or 0 ?

**Comment by Serpano** [comment]
thank you for the alternate method :) it works but i think when i add SpawnAfterDeath=GreenSlime.GreenSlime he spawns 2 greenslimes :)  ? it dont work take a look at this screenshot...

![image](https://cloud.githubusercontent.com/assets/20912432/23386272/c413ecfa-fd55-11e6-94f9-acf2c71428a1.png)

**Comment by Serpano** [comment]
why are the issue closed? :/

**Comment by Iyouboushi** [comment]
Pentium made a new request with the fix so this one can stay closed.
