### ISSUE TITLE
New Game Idea from a player on my Network

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#35]
A player in my network asked me if it is possible to give random monsters in round different strengths or weaknesses ... zb That he is immune in 1 round against swords .. in a further stop resistant to poison or so .. or Stop other things

Would be something sensible or implementable?
do you understand what i mean
Sry for my bad english i come from germany

**Comment by Iyouboushi** [comment]
Let's leave ISSUES for bugs and actual issues for the bot rather than suggestions.  I've created a Google Document for leaving suggestions and where we can discuss them. 

https://docs.google.com/document/d/1LAvrZH5JMetimigBDAC1ET2MHnuobOhLWTOg0tp-52E/edit
