### ISSUE TITLE
Supply Run Issue - Monster Attacking Error

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#39]
I Run the Bot on my Network
I Modified the Turnmessage in Translation.dat and the critical hit Code: 
by Default is was:
  `set %attack.damage $round($calc(%attack.damage * 1.5),0)`
i Change it to : 
`set %attack.damage $round($calc(%attack.damage * 2.5),0)`

now i'm at Arena Level 56 at Event Supply run,

A Monster gave's an error from attacking:
See at Pastebin: https://pastebin.com/68u9q0e8

Where could be the error ?

//edit
The Same error occurs on normal Events ...
p.s: The Enmity System is Enabled

At the Bot Window i fond this at Event Supply Run
> [BattleArena] Dune Widow steps up first in the battle!
target null

**Comment by Iyouboushi** [comment]
It's a mistake. I have a . instead of a _ for when it calls the random target alias.  It'll be fixed in a sec.
