### ISSUE TITLE
Suggestion - NPC  "Bots"

### ISSUE THREAD

**Issue by cdmichaelb** [Iyouboushi/mIRC-BattleArena#4]
I hope it's ok to post suggestions here, couldn't find any official place to post them.

Anyway, I think it'd be cool if the bot could logon additional bots for use of becoming NPCs. They could join on entering battle, then leave on death (or at end of battle; in which case change nick to monstername|dead). Would add a cool little element and make it easier to keep track of enemies in the fight.

**Comment by Iyouboushi** [comment]
Most IRC servers have a limit on the number of connections you could have.  As such this idea won't really work.

**Comment by AndrioCelos** [comment]
I actually tried this with my own IRC bot. The main problems are the aforementioned limit, and the fact that the names might be taken.
