### ISSUE TITLE
Issue or not ? i'm not sure...

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#40]
Hello at my Network at arenalevel 57

my Stats are: 
`[HP 8213/9350] [TP 485/500] [Ignition Gauge 0/0] [Level 54] [Armor Level 1] [Status Normal] [Royal Guard Meter 3372] [Capacity Points 141/10000] [Enhancement Points 0] [Login Points 470]
<BattleArena> [Strength: 191 +8] [Defense: 57 +12] [Intelligence: 600 +0][Speed: 238 +0]
<BattleArena> [Current Weapon Equipped Iridialstaff] [Current Accessory Wizard's-amulet] [Current Head Armor CrimsonCrown] [Current Body Armor CrimsonHauberk] [Current Leg Armor RUstyHose] [Current Feet Armor RustyBoots] [Current Hand Armor RustyKnuckles]`

And the Stats of the Player Shira are..
`[4HP12 105901/1210590] [4TP12 2501/12250] [4Ignition Gauge12 701/1270] [4Level12 6] [4Armor Level12 1] [4Status12 3Normal] [4Royal Guard Meter12 2599] [4Capacity Points12 1451/1210000] [4Enhancement Points12 0] [4Login Points12 280]
<BattleArena> [4Strength:12 290 3+3] [4Defense:12 197 3+7] [4Intelligence:12 295 3+5][4Speed:12 10 3+5]
<BattleArena> [4Current Weapon Equipped 12yewwand] [4Current Accessory 123Treasure-Ring] [4Current Head Armor 12BucketHat] [4Current Body Armor 12Tornrobe] [4Current Leg Armor 12RustyHose] [4Current Feet Armor 12RustyBoots] [4Current Hand Armor 12RustyKnuckles]`

So here is my QUestion:

Why takes shira more damage than me?
`<@BattleArena> Decapiclops spits a large ball of fire at the battlefield, which then explodes to hit everyone on the field!
<@BattleArena> The attack did 74 damage to Serpano! Flames swell up around Serpano's body! 
<@BattleArena> The attack did 1,422 damage to Shira! Shira's body begins to smoke as flames swell and burn! 

?

**Comment by AndrioCelos** [comment]
Which damage formula were you using?

**Comment by Serpano** [comment]
Standard ... i dont Change it.

**Comment by Pentium320** [comment]
I'm only guessing, but battlefield events may take some percentage from total HP, not a fixed amount. Same thing occurs with *status effects*, like burning, shocked, etc. *Spirit of the Hero* buff also makes some adjustments to overall damage. Though, I'm also not sure if this should be assumed as bug, or it's intended to be like that.

**Comment by Serpano** [comment]
issue closed - it maybe her int + def value are not high enough ..

**Comment by Tiranadel** [comment]
I know this is a late reply, but I'll do so anyway.

Battlefield events used to be a percent, but it was then set to fixed amount. Or at least I think so, I might be wrong on that since it's been a while on this. Status effects, however, are based on a percent. The higher the HP, the more it does. If you set your HP to an amount that you can't get normally, you can get an idea. I'm not sure on Spirit of the Hero though.

Also, I think the percent thing applies to techs/attacks as well, so it's most likely both that and the lower stats. Anyway, I'll close this issue in a day or two.
