### ISSUE TITLE
Sleeppowder tech issue

### ISSUE THREAD

**Issue by Serpano** [Iyouboushi/mIRC-BattleArena#42]
Hello anybody - i need help for a tech on my network:
The Bot says the Following Output:

`* +Serpano uses his Sleeppowder on Mamm`
`<@BattleArenaBot> Wooly Mammoth is no longer asleep!`
`<@BattleArenaBot> Serpano Sprays powder that allows the person who inhales it to fall asleep.`
`<@BattleArenaBot> The attack does 105 damage to Wooly Mammoth. [Don't Worry]`
`<@BattleArenaBot> Wooly Mammoth is now asleep!`
`<@BattleArenaBot> A cold arctic wind blows as the clouds begin to grace the battlfield with snow`
`<@BattleArenaBot> It is Wooly Mammoth's turn [Health Bar:(||||||||||) 2621 / 2726 - Great] [Status Effects: Normal] [Active Skills: None]`

And there is the code for the tech in the techniques.db:
`[SleepPowder]`
`Type=Single`
`cost=0`
`Desc=Sprays powder that allows the person who inhales it to fall asleep.`
`TP=$rand(15,24)`
`Basepower=0`
`StatusType=sleep`

Now where is the error?

**Comment by AndrioCelos** [comment]
Looks like a quirk with the sleep status: it's falling asleep, then immediately waking up because it took damage.

**Comment by Serpano** [comment]
The same is when I use Asian Mist tech now I could sleep powder should be the target to be sleeping but I don't know where is the code i just another Technik with the sleep Status it does the same effect the target not sleeping how can I fix this

**Comment by AndrioCelos** [comment]
Perhaps moving the code that inflicts the sleep status (in the damage calculation algorithms) to just _after_ that which wakes it up (in `deal_damage`) would work.

**Comment by Serpano** [comment]
I Test it with the BlueAsianMist tech the Same Effekt See at the Top of the thread  the  bot says the same..

**Comment by Serpano** [comment]
When I use it be Instrument the sleep Status that work but when I use it on a tech it dont work both tech in the techniques.db the standardtech blueasianmist dont work ans my Own. Sleeppowdertech..

**Comment by Serpano** [comment]
Can you help me? To fix IT?

**Comment by Serpano** [comment]
I will that the tech works how can i do this?

**Comment by Tiranadel** [comment]
Well, I suppose that's my fault for not actually seeing if sleep status can work with techs or attacks. Andrio is right, in that the sleep status is being applied first, then it's removed when the damage happens.

I did tell Iyou about it, and he said it would basically mean doing a ton of re-coding for it to work, so it might not be changed on this. So in this case, I'm going to change the BlueAsianMist tech to apply another status effect soon. Hopefully I can do that in a day or two.

**Comment by Iyouboushi** [comment]
Yeah, I meant to come reply here too but forgot.  Smz is right.  In Battle Arena inflict_status is done in the damage formulas right now.  That means the status is applied while the bot is still figuring out how much damage is done and before the damage is actually applied.  Then when the damage formula is done the bot moves into a "deal damage" code block where the damage is applied and since the sleep status is applied first it's immediately wearing off.

The solution would be to move inflict_status to a later point but it would require a lot of recoding to make work properly and I'm kind of busy working on the new bot (which won't have this problem as inflict status is done after the deal damage part of the bot).

**Comment by Serpano** [comment]
yes i see your new Projekt and i find it its a good idea... i hope this will bee a good irc game :)
now i has recoded the awake code for a third if clause but i dont be sure if it fully works .. at the lower arena level yes but for higher level hmm ?

the code is the following:
`; Do we need to wake up a sleeping target?`
  `if ((%attack.damage < 0) && ($readini($char($2), Status, sleep) = yes) && ($readini($char($2), Status, burning) = yes)) { `
    `$display.message($readini(translation.dat, status, WakesUp), battle) `
    `writeini $char($2) status sleep no`
 ` }`

**Comment by Serpano** [comment]
hmm the code is nice and works but not fully function .. i remove the if clause.. because ...
If darkness occured and the monster is curently asleep it dont awake if i set him in flame...

i remove the code and set it to normaly... :/ now i use for sleepowder inimidate
but is has no the same effect of sleep..
